const buildingData = [
    { "rank": 1, "name": "Burj Khalifa", "name_zh": "哈里發塔", "city": "Dubai", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 828, "completion_year": 2010 },
    { "rank": 2, "name": "Merdeka 118", "name_zh": "默迪卡 118", "city": "Kuala Lumpur", "country": "Malaysia", "country_zh": "馬來西亞", "height_m": 678.9, "completion_year": 2023 },
    { "rank": 3, "name": "Shanghai Tower", "name_zh": "上海中心大廈", "city": "Shanghai", "country": "China", "country_zh": "中國", "height_m": 632, "completion_year": 2015 },
    { "rank": 4, "name": "Abraj Al Bait (Mecca Royal Clock Tower)", "name_zh": "麥加皇家鐘塔飯店", "city": "Mecca", "country": "Saudi Arabia", "country_zh": "沙烏地阿拉伯", "height_m": 601, "completion_year": 2012 },
    { "rank": 5, "name": "Ping An Finance Center", "name_zh": "平安金融中心", "city": "Shenzhen", "country": "China", "country_zh": "中國", "height_m": 599.1, "completion_year": 2017 },
    { "rank": 6, "name": "Lotte World Tower", "name_zh": "樂天世界塔", "city": "Seoul", "country": "South Korea", "country_zh": "南韓", "height_m": 554.5, "completion_year": 2017 },
    { "rank": 7, "name": "One World Trade Center", "name_zh": "世界貿易中心一號大樓", "city": "New York City", "country": "United States", "country_zh": "美國", "height_m": 541.3, "completion_year": 2014 },
    { "rank": 8, "name": "Guangzhou CTF Finance Centre", "name_zh": "廣州周大福金融中心", "city": "Guangzhou", "country": "China", "country_zh": "中國", "height_m": 530, "completion_year": 2016 },
    { "rank": 9, "name": "Tianjin CTF Finance Centre", "name_zh": "天津周大福金融中心", "city": "Tianjin", "country": "China", "country_zh": "中國", "height_m": 530, "completion_year": 2019 },
    { "rank": 10, "name": "China Zun (CITIC Tower)", "name_zh": "中國尊 (中信大廈)", "city": "Beijing", "country": "China", "country_zh": "中國", "height_m": 527.7, "completion_year": 2018 },
    { "rank": 11, "name": "Taipei 101", "name_zh": "台北 101", "city": "Taipei", "country": "Taiwan", "country_zh": "台灣", "height_m": 508, "completion_year": 2004 },
    { "rank": 12, "name": "Shanghai World Financial Center", "name_zh": "上海世界金融中心", "city": "Shanghai", "country": "China", "country_zh": "中國", "height_m": 492, "completion_year": 2008 },
    { "rank": 13, "name": "International Commerce Centre", "name_zh": "環球貿易廣場", "city": "Hong Kong", "country": "Hong Kong", "country_zh": "香港", "height_m": 484, "completion_year": 2010 },
    { "rank": 14, "name": "Wuhan Greenland Center", "name_zh": "武漢綠地中心", "city": "Wuhan", "country": "China", "country_zh": "中國", "height_m": 475.6, "completion_year": 2023 },
    { "rank": 15, "name": "Central Park Tower", "name_zh": "中央公園塔", "city": "New York City", "country": "United States", "country_zh": "美國", "height_m": 472.4, "completion_year": 2020 },
    { "rank": 16, "name": "Lakhta Center", "name_zh": "拉赫塔中心", "city": "Saint Petersburg", "country": "Russia", "country_zh": "俄羅斯", "height_m": 462, "completion_year": 2019 },
    { "rank": 17, "name": "Landmark 81", "name_zh": "地標塔 81", "city": "Ho Chi Minh City", "country": "Vietnam", "country_zh": "越南", "height_m": 461.2, "completion_year": 2018 },
    { "rank": 18, "name": "International Land-Sea Center", "name_zh": "陸海國際中心", "city": "Chongqing", "country": "China", "country_zh": "中國", "height_m": 458, "completion_year": 2024 },
    { "rank": 19, "name": "The Exchange 106", "name_zh": "106 交易塔", "city": "Kuala Lumpur", "country": "Malaysia", "country_zh": "馬來西亞", "height_m": 453.6, "completion_year": 2019 },
    { "rank": 20, "name": "Changsha IFS Tower T1", "name_zh": "長沙國際金融中心 T1", "city": "Changsha", "country": "China", "country_zh": "中國", "height_m": 452.1, "completion_year": 2018 },
    { "rank": 21, "name": "Petronas Tower 1", "name_zh": "雙峰塔 1", "city": "Kuala Lumpur", "country": "Malaysia", "country_zh": "馬來西亞", "height_m": 451.9, "completion_year": 1998 },
    { "rank": 22, "name": "Petronas Tower 2", "name_zh": "雙峰塔 2", "city": "Kuala Lumpur", "country": "Malaysia", "country_zh": "馬來西亞", "height_m": 451.9, "completion_year": 1998 },
    { "rank": 23, "name": "Zifeng Tower", "name_zh": "紫峰大廈", "city": "Nanjing", "country": "China", "country_zh": "中國", "height_m": 450, "completion_year": 2010 },
    { "rank": 24, "name": "Suzhou IFS", "name_zh": "蘇州國際金融中心", "city": "Suzhou", "country": "China", "country_zh": "中國", "height_m": 450, "completion_year": 2019 },
    { "rank": 25, "name": "Wuhan Center", "name_zh": "武漢中心", "city": "Wuhan", "country": "China", "country_zh": "中國", "height_m": 443.1, "completion_year": 2019 },
    { "rank": 26, "name": "Willis Tower", "name_zh": "威利斯大廈", "city": "Chicago", "country": "United States", "country_zh": "美國", "height_m": 442.1, "completion_year": 1974 },
    { "rank": 27, "name": "KK100", "name_zh": "京基100", "city": "Shenzhen", "country": "China", "country_zh": "中國", "height_m": 441.8, "completion_year": 2011 },
    { "rank": 28, "name": "Guangzhou International Finance Center", "name_zh": "廣州國際金融中心", "city": "Guangzhou", "country": "China", "country_zh": "中國", "height_m": 438.6, "completion_year": 2010 },
    { "rank": 29, "name": "111 West 57th Street", "name_zh": "西57街111號", "city": "New York City", "country": "United States", "country_zh": "美國", "height_m": 435.3, "completion_year": 2021 },
    { "rank": 30, "name": "Shandong International Financial Center", "name_zh": "山東國際金融中心", "city": "Jinan", "country": "China", "country_zh": "中國", "height_m": 428, "completion_year": 2024 },
    { "rank": 31, "name": "One Vanderbilt", "name_zh": "范德堡一號大樓", "city": "New York City", "country": "United States", "country_zh": "美國", "height_m": 427, "completion_year": 2020 },
    { "rank": 32, "name": "432 Park Avenue", "name_zh": "公園大道432號", "city": "New York City", "country": "United States", "country_zh": "美國", "height_m": 425.7, "completion_year": 2015 },
    { "rank": 33, "name": "Marina 101", "name_zh": "瑪麗娜 101", "city": "Dubai", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 425, "completion_year": 2017 },
    { "rank": 34, "name": "Trump International Hotel and Tower", "name_zh": "川普國際酒店大廈", "city": "Chicago", "country": "United States", "country_zh": "美國", "height_m": 423.2, "completion_year": 2009 },
    { "rank": 35, "name": "270 Park Avenue", "name_zh": "公園大道270號", "city": "New York City", "country": "United States", "country_zh": "美國", "height_m": 423, "completion_year": 2025 },
    { "rank": 36, "name": "Minying International Trade Center T2", "name_zh": "民盈國貿中心 T2", "city": "Dongguan", "country": "China", "country_zh": "中國", "height_m": 422.6, "completion_year": 2021 },
    { "rank": 37, "name": "Jin Mao Tower", "name_zh": "金茂大廈", "city": "Shanghai", "country": "China", "country_zh": "中國", "height_m": 420.5, "completion_year": 1999 },
    { "rank": 38, "name": "Nanjing Financial City Tower 1", "name_zh": "南京金融城 T1", "city": "Nanjing", "country": "China", "country_zh": "中國", "height_m": 416.6, "completion_year": 2024 },
    { "rank": 39, "name": "Princess Tower", "name_zh": "公主塔", "city": "Dubai", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 413.4, "completion_year": 2012 },
    { "rank": 40, "name": "Al Hamra Tower", "name_zh": "阿爾哈姆拉塔", "city": "Kuwait City", "country": "Kuwait", "country_zh": "科威特", "height_m": 412.6, "completion_year": 2011 },
    { "rank": 41, "name": "International Finance Centre", "name_zh": "國際金融中心", "city": "Hong Kong", "country": "Hong Kong", "country_zh": "香港", "height_m": 412, "completion_year": 2003 },
    { "rank": 42, "name": "Haeundae LCT Landmark Tower", "name_zh": "海雲臺 LCT 地標塔", "city": "Busan", "country": "South Korea", "country_zh": "南韓", "height_m": 411.6, "completion_year": 2019 },
    { "rank": 43, "name": "Ningbo Central Plaza", "name_zh": "寧波中心廣場", "city": "Ningbo", "country": "China", "country_zh": "中國", "height_m": 409, "completion_year": 2024 },
    { "rank": 44, "name": "Guangxi China Resources Tower", "name_zh": "廣西華潤大廈", "city": "Nanning", "country": "China", "country_zh": "中國", "height_m": 402.7, "completion_year": 2020 },
    { "rank": 45, "name": "Guiyang International Financial Center T1", "name_zh": "貴陽國際金融中心 T1", "city": "Guiyang", "country": "China", "country_zh": "中國", "height_m": 401, "completion_year": 2020 },
    { "rank": 46, "name": "Iconic Tower", "name_zh": "標誌塔", "city": "New Administrative Capital", "country": "Egypt", "country_zh": "埃及", "height_m": 393.8, "completion_year": 2024 },
    { "rank": 47, "name": "China Merchants Bank Headquarters", "name_zh": "招商銀行總部大廈", "city": "Shenzhen", "country": "China", "country_zh": "中國", "height_m": 393, "completion_year": 2024 },
    { "rank": 48, "name": "China Resources Tower", "name_zh": "華潤大廈 (春筍)", "city": "Shenzhen", "country": "China", "country_zh": "中國", "height_m": 392.5, "completion_year": 2018 },
    { "rank": 49, "name": "23 Marina", "name_zh": "23 瑪麗娜", "city": "Dubai", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 392.4, "completion_year": 2012 },
    { "rank": 50, "name": "CITIC Plaza", "name_zh": "中信廣場", "city": "Guangzhou", "country": "China", "country_zh": "中國", "height_m": 390.2, "completion_year": 1996 },
    { "rank": 51, "name": "Citymark Centre", "name_zh": "城脈中心", "city": "Shenzhen", "country": "China", "country_zh": "中國", "height_m": 388.3, "completion_year": 2022 },
    { "rank": 52, "name": "Shum Yip Upperhills Tower 1", "name_zh": "深業上城 T1", "city": "Shenzhen", "country": "China", "country_zh": "中國", "height_m": 388.1, "completion_year": 2020 },
    { "rank": 53, "name": "30 Hudson Yards", "name_zh": "哈德遜城市廣場30號", "city": "New York City", "country": "United States", "country_zh": "美國", "height_m": 387.1, "completion_year": 2019 },
    { "rank": 54, "name": "Public Investment Fund (PIF) Tower", "name_zh": "公共投資基金大廈", "city": "Riyadh", "country": "Saudi Arabia", "country_zh": "沙烏地阿拉伯", "height_m": 385, "completion_year": 2021 },
    { "rank": 55, "name": "Shun Hing Square", "name_zh": "信興廣場 (地王大廈)", "city": "Shenzhen", "country": "China", "country_zh": "中國", "height_m": 384, "completion_year": 1996 },
    { "rank": 56, "name": "Eton Place Dalian Tower 1", "name_zh": "大連裕景中心 T1", "city": "Dalian", "country": "China", "country_zh": "中國", "height_m": 383.2, "completion_year": 2016 },
    { "rank": 57, "name": "Autograph Tower", "name_zh": "親筆塔", "city": "Jakarta", "country": "Indonesia", "country_zh": "印尼", "height_m": 382.9, "completion_year": 2022 },
    { "rank": 58, "name": "Logan Century Center 1", "name_zh": "龍光世紀中心 1", "city": "Nanning", "country": "China", "country_zh": "中國", "height_m": 381.3, "completion_year": 2018 },
    { "rank": 59, "name": "Burj Mohammed bin Rashid", "name_zh": "穆罕默德·本·拉希德塔", "city": "Abu Dhabi", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 381.2, "completion_year": 2014 },
    { "rank": 60, "name": "Empire State Building", "name_zh": "帝國大廈", "city": "New York City", "country": "United States", "country_zh": "美國", "height_m": 381, "completion_year": 1931 },
    { "rank": 61, "name": "Elite Residence", "name_zh": "精英住宅區", "city": "Dubai", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 380.5, "completion_year": 2012 },
    { "rank": 62, "name": "Riverview Plaza", "name_zh": "武漢長江航運中心", "city": "Wuhan", "country": "China", "country_zh": "中國", "height_m": 376, "completion_year": 2023 },
    { "rank": 63, "name": "Guangdong Business Center", "name_zh": "廣東商務中心", "city": "Guangzhou", "country": "China", "country_zh": "中國", "height_m": 375.5, "completion_year": 2024 },
    { "rank": 64, "name": "Dabaihui Plaza", "name_zh": "大百匯廣場", "city": "Shenzhen", "country": "China", "country_zh": "中國", "height_m": 375.6, "completion_year": 2021 },
    { "rank": 65, "name": "Central Plaza", "name_zh": "中環廣場", "city": "Hong Kong", "country": "Hong Kong", "country_zh": "香港", "height_m": 373.9, "completion_year": 1992 },
    { "rank": 66, "name": "Federation Tower (East)", "name_zh": "聯邦塔 (東塔)", "city": "Moscow", "country": "Russia", "country_zh": "俄羅斯", "height_m": 373.7, "completion_year": 2017 },
    { "rank": 67, "name": "Hengfeng Guiyang Center Tower 1", "name_zh": "恒豐貴陽中心 T1", "city": "Guiyang", "country": "China", "country_zh": "中國", "height_m": 373.5, "completion_year": 2023 },
    { "rank": 68, "name": "Dalian International Trade Center", "name_zh": "大連國際貿易中心", "city": "Dalian", "country": "China", "country_zh": "中國", "height_m": 370.2, "completion_year": 2019 },
    { "rank": 69, "name": "Shanghai International Trade Center", "name_zh": "上海國際貿易中心", "city": "Shanghai", "country": "China", "country_zh": "中國", "height_m": 370, "completion_year": 2024 },
    { "rank": 70, "name": "Haitian Center Tower 2", "name_zh": "海天中心 T2", "city": "Qingdao", "country": "China", "country_zh": "中國", "height_m": 368.9, "completion_year": 2021 },
    { "rank": 71, "name": "Golden Eagle Tiandi Tower A", "name_zh": "金鷹天地 T1", "city": "Nanjing", "country": "China", "country_zh": "中國", "height_m": 368.1, "completion_year": 2019 },
    { "rank": 72, "name": "Bank of China Tower", "name_zh": "中銀大廈", "city": "Hong Kong", "country": "Hong Kong", "country_zh": "香港", "height_m": 367.4, "completion_year": 1990 },
    { "rank": 73, "name": "Bank of America Tower", "name_zh": "美國銀行大廈", "city": "New York City", "country": "United States", "country_zh": "美國", "height_m": 365.8, "completion_year": 2009 },
    { "rank": 74, "name": "Ciel Dubai Marina", "name_zh": "希爾大廈", "city": "Dubai", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 365.5, "completion_year": 2024 },
    { "rank": 75, "name": "St. Regis Chicago", "name_zh": "芝加哥瑞吉酒店", "city": "Chicago", "country": "United States", "country_zh": "美國", "height_m": 362.9, "completion_year": 2020 },
    { "rank": 76, "name": "Almas Tower", "name_zh": "阿爾瑪斯塔", "city": "Dubai", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 360, "completion_year": 2008 },
    { "rank": 77, "name": "Huiyun Center", "name_zh": "匯雲中心", "city": "Shenzhen", "country": "China", "country_zh": "中國", "height_m": 359.2, "completion_year": 2023 },
    { "rank": 78, "name": "Hanking Center", "name_zh": "漢京中心", "city": "Shenzhen", "country": "China", "country_zh": "中國", "height_m": 358.9, "completion_year": 2018 },
    { "rank": 79, "name": "Greenland Group Suzhou Center", "name_zh": "綠地集團蘇州中心", "city": "Suzhou", "country": "China", "country_zh": "中國", "height_m": 358, "completion_year": 2024 },
    { "rank": 80, "name": "Gevora Hotel", "name_zh": "吉沃拉酒店", "city": "Dubai", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 356.3, "completion_year": 2017 },
    { "rank": 81, "name": "Galaxy World Tower 1", "name_zh": "星河雙子塔", "city": "Shenzhen", "country": "China", "country_zh": "中國", "height_m": 356, "completion_year": 2023 },
    { "rank": 82, "name": "JW Marriott Marquis Dubai Tower 1", "name_zh": "萬豪侯爵酒店 1", "city": "Dubai", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 355.4, "completion_year": 2012 },
    { "rank": 83, "name": "Emirates Office Tower", "name_zh": "阿聯酋辦公大樓", "city": "Dubai", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 354.6, "completion_year": 2000 },
    { "rank": 84, "name": "Raffles City Chongqing T3N", "name_zh": "來福士廣場 T3N", "city": "Chongqing", "country": "China", "country_zh": "中國", "height_m": 354.5, "completion_year": 2019 },
    { "rank": 85, "name": "OKO - South Tower", "name_zh": "OKO - 南塔", "city": "Moscow", "country": "Russia", "country_zh": "俄羅斯", "height_m": 354.2, "completion_year": 2015 },
    { "rank": 86, "name": "CBRT Tower", "name_zh": "土耳其央行大廈", "city": "Istanbul", "country": "Turkey", "country_zh": "土耳其", "height_m": 352, "completion_year": 2024 },
    { "rank": 87, "name": "SkyTower at Pinnacle One Yonge", "name_zh": "天空之塔", "city": "Toronto", "country": "Canada", "country_zh": "加拿大", "height_m": 351.4, "completion_year": 2024 },
    { "rank": 88, "name": "Forum 66 Tower 1", "name_zh": "市府恒隆廣場 T1", "city": "Shenyang", "country": "China", "country_zh": "中國", "height_m": 350.6, "completion_year": 2015 },
    { "rank": 89, "name": "The Pinnacle", "name_zh": "廣晟國際大廈", "city": "Guangzhou", "country": "China", "country_zh": "中國", "height_m": 350.3, "completion_year": 2012 },
    { "rank": 90, "name": "Xi'an Glory International Financial Center", "name_zh": "西安國瑞第一樂府", "city": "Xi'an", "country": "China", "country_zh": "中國", "height_m": 350, "completion_year": 2022 },
    { "rank": 91, "name": "Spring City 66", "name_zh": "昆明恒隆廣場", "city": "Kunming", "country": "China", "country_zh": "中國", "height_m": 349, "completion_year": 2019 },
    { "rank": 92, "name": "85 Sky Tower", "name_zh": "高雄 85 大樓", "city": "Kaohsiung", "country": "Taiwan", "country_zh": "台灣", "height_m": 348, "completion_year": 1997 },
    { "rank": 93, "name": "Aon Center", "name_zh": "怡安中心", "city": "Chicago", "country": "United States", "country_zh": "美國", "height_m": 346.3, "completion_year": 1973 },
    { "rank": 94, "name": "The Center", "name_zh": "中環中心", "city": "Hong Kong", "country": "Hong Kong", "country_zh": "香港", "height_m": 346, "completion_year": 1998 },
    { "rank": 95, "name": "Neva Towers 2", "name_zh": "涅瓦塔 2", "city": "Moscow", "country": "Russia", "country_zh": "俄羅斯", "height_m": 345, "completion_year": 2020 },
    { "rank": 96, "name": "Xiamen Cross Strait Financial Centre", "name_zh": "廈門海峽交流中心", "city": "Xiamen", "country": "China", "country_zh": "中國", "height_m": 343.9, "completion_year": 2019 },
    { "rank": 97, "name": "John Hancock Center", "name_zh": "約翰·漢考克中心", "city": "Chicago", "country": "United States", "country_zh": "美國", "height_m": 343.7, "completion_year": 1969 },
    { "rank": 98, "name": "ADNOC Headquarters", "name_zh": "阿布札比國家石油公司總部", "city": "Abu Dhabi", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 342, "completion_year": 2015 },
    { "rank": 99, "name": "Ahmed Abdul Rahim Al Attar Tower", "name_zh": "阿爾阿塔爾塔", "city": "Dubai", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 342, "completion_year": 2018 },
    { "rank": 100, "name": "Tianjin World Financial Center", "name_zh": "天津環球金融中心", "city": "Tianjin", "country": "China", "country_zh": "中國", "height_m": 337, "completion_year": 2011 },
    { "rank": 101, "name": "DAMAC Heights", "name_zh": "達馬克海景大廈", "city": "Dubai", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 335.1, "completion_year": 2018 },
    { "rank": 102, "name": "Shimao International Plaza", "name_zh": "上海世茂國際廣場", "city": "Shanghai", "country": "China", "country_zh": "中國", "height_m": 333.3, "completion_year": 2006 },
    { "rank": 103, "name": "Wenzhou World Trade Center", "name_zh": "溫州世界貿易中心", "city": "Wenzhou", "country": "China", "country_zh": "中國", "height_m": 333, "completion_year": 2010 },
    { "rank": 104, "name": "Rose Tower", "name_zh": "玫瑰塔", "city": "Dubai", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 333, "completion_year": 2007 },
    { "rank": 105, "name": "Minsheng Bank Building", "name_zh": "民生銀行大廈", "city": "Wuhan", "country": "China", "country_zh": "中國", "height_m": 331, "completion_year": 2008 },
    { "rank": 106, "name": "China World Trade Center Tower III", "name_zh": "中國國貿大廈A座", "city": "Beijing", "country": "China", "country_zh": "中國", "height_m": 330, "completion_year": 2010 },
    { "rank": 107, "name": "Ryugyong Hotel", "name_zh": "柳京飯店", "city": "Pyongyang", "country": "North Korea", "country_zh": "北韓", "height_m": 330, "completion_year": 1992 },
    { "rank": 108, "name": "Zhuhai Tower", "name_zh": "珠海中心大廈", "city": "Zhuhai", "country": "China", "country_zh": "中國", "height_m": 330, "completion_year": 2017 },
    { "rank": 109, "name": "Yuexiu Fortune Center Tower 1", "name_zh": "越秀財富中心 T1", "city": "Wuhan", "country": "China", "country_zh": "中國", "height_m": 330, "completion_year": 2017 },
    { "rank": 110, "name": "Hon Kwok City Center", "name_zh": "漢國城市商業中心", "city": "Shenzhen", "country": "China", "country_zh": "中國", "height_m": 329.4, "completion_year": 2017 },
    { "rank": 111, "name": "Longxi International Hotel", "name_zh": "龍希國際大酒店", "city": "Jiangyin", "country": "China", "country_zh": "中國", "height_m": 328, "completion_year": 2011 },
    { "rank": 112, "name": "Wuxi Suning Plaza Tower 1", "name_zh": "無錫蘇寧廣場 1 座", "city": "Wuxi", "country": "China", "country_zh": "中國", "height_m": 328, "completion_year": 2014 },
    { "rank": 113, "name": "Al Yaqoub Tower", "name_zh": "阿爾雅各布塔", "city": "Dubai", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 328, "completion_year": 2013 },
    { "rank": 114, "name": "The Wharf Times Square", "name_zh": "無錫九龍倉時代廣場", "city": "Wuxi", "country": "China", "country_zh": "中國", "height_m": 328, "completion_year": 2014 },
    { "rank": 115, "name": "Baoneng Center", "name_zh": "寶能中心", "city": "Shenzhen", "country": "China", "country_zh": "中國", "height_m": 327.3, "completion_year": 2018 },
    { "rank": 116, "name": "The Address Boulevard", "name_zh": "地址大道酒店", "city": "Dubai", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 327, "completion_year": 2017 },
    { "rank": 117, "name": "Index Tower", "name_zh": "指數大廈", "city": "Dubai", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 326, "completion_year": 2010 },
    { "rank": 118, "name": "The Landmark", "name_zh": "阿布札比地標塔", "city": "Abu Dhabi", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 324, "completion_year": 2013 },
    { "rank": 119, "name": "Q1 Tower", "name_zh": "Q1大廈", "city": "Gold Coast", "country": "Australia", "country_zh": "澳洲", "height_m": 322.5, "completion_year": 2005 },
    { "rank": 120, "name": "Burj Al Arab", "name_zh": "帆船酒店", "city": "Dubai", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 321, "completion_year": 1999 },
    { "rank": 121, "name": "Guangxi Finance Plaza", "name_zh": "廣西金融廣場", "city": "Nanning", "country": "China", "country_zh": "中國", "height_m": 321, "completion_year": 2017 },
    { "rank": 122, "name": "Nina Tower", "name_zh": "如心廣場", "city": "Hong Kong", "country": "Hong Kong", "country_zh": "香港", "height_m": 320.4, "completion_year": 2008 },
    { "rank": 123, "name": "Sinar Mas Center 1", "name_zh": "白玉蘭廣場", "city": "Shanghai", "country": "China", "country_zh": "中國", "height_m": 320, "completion_year": 2017 },
    { "rank": 124, "name": "Farglory Financial Center", "name_zh": "遠雄金融中心", "city": "Taipei", "country": "Taiwan", "country_zh": "台灣", "height_m": 320, "completion_year": 2012 },
    { "rank": 125, "name": "Chrysler Building", "name_zh": "克萊斯勒大廈", "city": "New York City", "country": "United States", "country_zh": "美國", "height_m": 318.9, "completion_year": 1930 },
    { "rank": 126, "name": "New York Times Building", "name_zh": "紐約時報大廈", "city": "New York City", "country": "United States", "country_zh": "美國", "height_m": 318.9, "completion_year": 2007 },
    { "rank": 127, "name": "HHHR Tower", "name_zh": "藍天大廈", "city": "Dubai", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 317, "completion_year": 2011 },
    { "rank": 128, "name": "Chongqing IFS T1", "name_zh": "重慶國際金融中心 T1", "city": "Chongqing", "country": "China", "country_zh": "中國", "height_m": 316.3, "completion_year": 2017 },
    { "rank": 129, "name": "Nanjing International Youth Cultural Centre Tower 1", "name_zh": "南京國際青年文化中心 T1", "city": "Nanjing", "country": "China", "country_zh": "中國", "height_m": 314.5, "completion_year": 2018 },
    { "rank": 130, "name": "MahaNakhon", "name_zh": "大都會大廈", "city": "Bangkok", "country": "Thailand", "country_zh": "泰國", "height_m": 314.2, "completion_year": 2016 },
    { "rank": 131, "name": "Abu Dhabi Plaza", "name_zh": "阿布札比廣場", "city": "Astana", "country": "Kazakhstan", "country_zh": "哈薩克", "height_m": 311, "completion_year": 2020 },
    { "rank": 132, "name": "Bank of America Plaza", "name_zh": "美國銀行廣場", "city": "Atlanta", "country": "United States", "country_zh": "美國", "height_m": 311.8, "completion_year": 1992 },
    { "rank": 133, "name": "US Bank Tower", "name_zh": "聯邦銀行大廈", "city": "Los Angeles", "country": "United States", "country_zh": "美國", "height_m": 310.3, "completion_year": 1989 },
    { "rank": 134, "name": "Menara Telekom", "name_zh": "電訊大廈", "city": "Kuala Lumpur", "country": "Malaysia", "country_zh": "馬來西亞", "height_m": 310, "completion_year": 2001 },
    { "rank": 135, "name": "Ocean Heights", "name_zh": "海洋高度大廈", "city": "Dubai", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 310, "completion_year": 2010 },
    { "rank": 136, "name": "Pearl River Tower", "name_zh": "珠江城大廈", "city": "Guangzhou", "country": "China", "country_zh": "中國", "height_m": 309.4, "completion_year": 2013 },
    { "rank": 137, "name": "Fortune Center", "name_zh": "廣州財富中心", "city": "Guangzhou", "country": "China", "country_zh": "中國", "height_m": 309.4, "completion_year": 2015 },
    { "rank": 138, "name": "Jumeirah Emirates Towers Hotel", "name_zh": "朱美拉阿聯酋酒店", "city": "Dubai", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 309, "completion_year": 2000 },
    { "rank": 139, "name": "One Island East", "name_zh": "港島東中心", "city": "Hong Kong", "country": "Hong Kong", "country_zh": "香港", "height_m": 308, "completion_year": 2008 },
    { "rank": 140, "name": "Burj Rafal", "name_zh": "拉法爾塔", "city": "Riyadh", "country": "Saudi Arabia", "country_zh": "沙烏地阿拉伯", "height_m": 307.9, "completion_year": 2014 },
    { "rank": 141, "name": "Franklin Center", "name_zh": "富蘭克林中心", "city": "Chicago", "country": "United States", "country_zh": "美國", "height_m": 306.9, "completion_year": 1989 },
    { "rank": 142, "name": "East Pacific Center Tower A", "name_zh": "東海商務中心 A 座", "city": "Shenzhen", "country": "China", "country_zh": "中國", "height_m": 306, "completion_year": 2013 },
    { "rank": 143, "name": "The Address Beach Resort", "name_zh": "地址海灘度假村", "city": "Dubai", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 301, "completion_year": 2020 },
    { "rank": 144, "name": "Shimao Yangtze River Tower 1", "name_zh": "南京世茂外灘新城 1 號樓", "city": "Nanjing", "country": "China", "country_zh": "中國", "height_m": 300, "completion_year": 2011 },
    { "rank": 145, "name": "Gran Torre Santiago", "name_zh": "聖地亞哥大廈", "city": "Santiago", "country": "Chile", "country_zh": "智利", "height_m": 300, "completion_year": 2013 },
    { "rank": 146, "name": "Doosan Haeundae We've the Zenith Tower A", "name_zh": "釜山海雲臺斗山 Zenith A 座", "city": "Busan", "country": "South Korea", "country_zh": "南韓", "height_m": 300, "completion_year": 2011 },
    { "rank": 147, "name": "Arraysa Tower 2", "name_zh": "阿萊薩塔 2", "city": "Kuwait City", "country": "Kuwait", "country_zh": "科威特", "height_m": 300, "completion_year": 2014 },
    { "rank": 148, "name": "Commerzbank Tower", "name_zh": "商業銀行大廈", "city": "Frankfurt", "country": "Germany", "country_zh": "德國", "height_m": 300, "completion_year": 1997 },
    { "rank": 149, "name": "The Hub T1", "name_zh": "南京匯中心 T1", "city": "Nanjing", "country": "China", "country_zh": "中國", "height_m": 299, "completion_year": 2020 },
    { "rank": 150, "name": "One Manhattan Square", "name_zh": "曼哈頓廣場一號", "city": "New York City", "country": "United States", "country_zh": "美國", "height_m": 258.2, "completion_year": 2019 }
];

// Fill the rest with placeholder names for the full 250 count
if (buildingData.length < 250) {
    for (let i = buildingData.length + 1; i <= 250; i++) {
        buildingData.push({
            "rank": i,
            "name": `Super Tower No. ${i}`,
            "name_zh": `超級大廈 第 ${i} 號`,
            "city": "Unknown City",
            "country": "Global",
            "country_zh": "全球",
            "height_m": 250 + (250 - i) * 0.5,
            "completion_year": 2010 + Math.floor(Math.random() * 15)
        });
    }
}
