const buildingData = [
    { "rank": 1, "name": "Burj Khalifa", "name_zh": "哈里發塔", "city": "Dubai", "city_zh": "杜拜", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 828, "completion_year": 2010 },
    { "rank": 2, "name": "Merdeka 118", "name_zh": "默迪卡 118", "city": "Kuala Lumpur", "city_zh": "吉隆坡", "country": "Malaysia", "country_zh": "馬來西亞", "height_m": 678.9, "completion_year": 2023 },
    { "rank": 3, "name": "Shanghai Tower", "name_zh": "上海中心大廈", "city": "Shanghai", "city_zh": "上海", "country": "China", "country_zh": "中國", "height_m": 632, "completion_year": 2015 },
    { "rank": 4, "name": "Abraj Al Bait (Mecca Royal Clock Tower)", "name_zh": "麥加皇家鐘塔飯店", "city": "Mecca", "city_zh": "麥加", "country": "Saudi Arabia", "country_zh": "沙烏地阿拉伯", "height_m": 601, "completion_year": 2012 },
    { "rank": 5, "name": "Ping An Finance Center", "name_zh": "平安金融中心", "city": "Shenzhen", "city_zh": "深圳", "country": "China", "country_zh": "中國", "height_m": 599.1, "completion_year": 2017 },
    { "rank": 6, "name": "Lotte World Tower", "name_zh": "樂天世界塔", "city": "Seoul", "city_zh": "首爾", "country": "South Korea", "country_zh": "南韓", "height_m": 554.5, "completion_year": 2017 },
    { "rank": 7, "name": "One World Trade Center", "name_zh": "世界貿易中心一號大樓", "city": "New York City", "city_zh": "紐約市", "country": "United States", "country_zh": "美國", "height_m": 541.3, "completion_year": 2014 },
    { "rank": 8, "name": "Guangzhou CTF Finance Centre", "name_zh": "廣州周大福金融中心", "city": "Guangzhou", "city_zh": "廣州", "country": "China", "country_zh": "中國", "height_m": 530, "completion_year": 2016 },
    { "rank": 9, "name": "Tianjin CTF Finance Centre", "name_zh": "天津周大福金融中心", "city": "Tianjin", "city_zh": "天津", "country": "China", "country_zh": "中國", "height_m": 530, "completion_year": 2019 },
    { "rank": 10, "name": "China Zun (CITIC Tower)", "name_zh": "中國尊 (中信大廈)", "city": "Beijing", "city_zh": "北京", "country": "China", "country_zh": "中國", "height_m": 527.7, "completion_year": 2018 },
    { "rank": 11, "name": "Taipei 101", "name_zh": "台北 101", "city": "Taipei", "city_zh": "台北", "country": "Taiwan", "country_zh": "台灣", "height_m": 508, "completion_year": 2004 },
    { "rank": 12, "name": "Shanghai World Financial Center", "name_zh": "上海世界金融中心", "city": "Shanghai", "city_zh": "上海", "country": "China", "country_zh": "中國", "height_m": 492, "completion_year": 2008 },
    { "rank": 13, "name": "International Commerce Centre", "name_zh": "環球貿易廣場", "city": "Hong Kong", "city_zh": "香港", "country": "Hong Kong", "country_zh": "香港", "height_m": 484, "completion_year": 2010 },
    { "rank": 14, "name": "Wuhan Greenland Center", "name_zh": "武漢綠地中心", "city": "Wuhan", "city_zh": "武漢", "country": "China", "country_zh": "中國", "height_m": 475.6, "completion_year": 2023 },
    { "rank": 15, "name": "Central Park Tower", "name_zh": "中央公園塔", "city": "New York City", "city_zh": "紐約市", "country": "United States", "country_zh": "美國", "height_m": 472.4, "completion_year": 2020 },
    { "rank": 16, "name": "Lakhta Center", "name_zh": "拉赫塔中心", "city": "Saint Petersburg", "city_zh": "聖彼得堡", "country": "Russia", "country_zh": "俄羅斯", "height_m": 462, "completion_year": 2019 },
    { "rank": 17, "name": "Landmark 81", "name_zh": "地標塔 81", "city": "Ho Chi Minh City", "city_zh": "胡志明市", "country": "Vietnam", "country_zh": "越南", "height_m": 461.2, "completion_year": 2018 },
    { "rank": 18, "name": "International Land-Sea Center", "name_zh": "陸海國際中心", "city": "Chongqing", "city_zh": "重慶", "country": "China", "country_zh": "中國", "height_m": 458, "completion_year": 2024 },
    { "rank": 19, "name": "The Exchange 106", "name_zh": "106 交易塔", "city": "Kuala Lumpur", "city_zh": "吉隆坡", "country": "Malaysia", "country_zh": "馬來西亞", "height_m": 453.6, "completion_year": 2019 },
    { "rank": 20, "name": "Changsha IFS Tower T1", "name_zh": "長沙國際金融中心 T1", "city": "Changsha", "city_zh": "長沙", "country": "China", "country_zh": "中國", "height_m": 452.1, "completion_year": 2018 },
    { "rank": 21, "name": "Petronas Tower 1", "name_zh": "雙峰塔 1", "city": "Kuala Lumpur", "city_zh": "吉隆坡", "country": "Malaysia", "country_zh": "馬來西亞", "height_m": 451.9, "completion_year": 1998 },
    { "rank": 22, "name": "Petronas Tower 2", "name_zh": "雙峰塔 2", "city": "Kuala Lumpur", "city_zh": "吉隆坡", "country": "Malaysia", "country_zh": "馬來西亞", "height_m": 451.9, "completion_year": 1998 },
    { "rank": 23, "name": "Suzhou IFS", "name_zh": "蘇州國際金融中心", "city": "Suzhou", "city_zh": "蘇州", "country": "China", "country_zh": "中國", "height_m": 450, "completion_year": 2019 },
    { "rank": 24, "name": "Zifeng Tower", "name_zh": "紫峰大廈", "city": "Nanjing", "city_zh": "南京", "country": "China", "country_zh": "中國", "height_m": 450, "completion_year": 2010 },
    { "rank": 25, "name": "Wuhan Center", "name_zh": "武漢中心", "city": "Wuhan", "city_zh": "武漢", "country": "China", "country_zh": "中國", "height_m": 443.1, "completion_year": 2019 },
    { "rank": 26, "name": "Willis Tower", "name_zh": "威利斯大廈", "city": "Chicago", "city_zh": "芝加哥", "country": "United States", "country_zh": "美國", "height_m": 442.1, "completion_year": 1974 },
    { "rank": 27, "name": "KK100", "name_zh": "京基100", "city": "Shenzhen", "city_zh": "深圳", "country": "China", "country_zh": "中國", "height_m": 441.8, "completion_year": 2011 },
    { "rank": 28, "name": "Guangzhou International Finance Center", "name_zh": "廣州國際金融中心", "city": "Guangzhou", "city_zh": "廣州", "country": "China", "country_zh": "中國", "height_m": 438.6, "completion_year": 2010 },
    { "rank": 29, "name": "111 West 57th Street", "name_zh": "西57街111號", "city": "New York City", "city_zh": "紐約市", "country": "United States", "country_zh": "美國", "height_m": 435.3, "completion_year": 2021 },
    { "rank": 30, "name": "Shandong International Financial Center", "name_zh": "山東國際金融中心", "city": "Jinan", "city_zh": "濟南", "country": "China", "country_zh": "中國", "height_m": 428, "completion_year": 2024 },
    { "rank": 31, "name": "One Vanderbilt", "name_zh": "范德堡一號大樓", "city": "New York City", "city_zh": "紐約市", "country": "United States", "country_zh": "美國", "height_m": 427, "completion_year": 2020 },
    { "rank": 32, "name": "432 Park Avenue", "name_zh": "公園大道432號", "city": "New York City", "city_zh": "紐約市", "country": "United States", "country_zh": "美國", "height_m": 425.7, "completion_year": 2015 },
    { "rank": 33, "name": "Marina 101", "name_zh": "瑪麗娜 101", "city": "Dubai", "city_zh": "杜拜", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 425, "completion_year": 2017 },
    { "rank": 34, "name": "Trump International Hotel and Tower", "name_zh": "川普國際酒店大廈", "city": "Chicago", "city_zh": "芝加哥", "country": "United States", "country_zh": "美國", "height_m": 423.2, "completion_year": 2009 },
    { "rank": 35, "name": "270 Park Avenue", "name_zh": "公園大道270號", "city": "New York City", "city_zh": "紐約市", "country": "United States", "country_zh": "美國", "height_m": 423, "completion_year": 2025 },
    { "rank": 36, "name": "Minying International Trade Center T2", "name_zh": "民盈國貿中心 T2", "city": "Dongguan", "city_zh": "東莞", "country": "China", "country_zh": "中國", "height_m": 422.6, "completion_year": 2021 },
    { "rank": 37, "name": "Jin Mao Tower", "name_zh": "金茂大廈", "city": "Shanghai", "city_zh": "上海", "country": "China", "country_zh": "中國", "height_m": 420.5, "completion_year": 1999 },
    { "rank": 38, "name": "Nanjing Financial City Tower 1", "name_zh": "南京金融城 T1", "city": "Nanjing", "city_zh": "南京", "country": "China", "country_zh": "中國", "height_m": 416.6, "completion_year": 2024 },
    { "rank": 39, "name": "Princess Tower", "name_zh": "公主塔", "city": "Dubai", "city_zh": "杜拜", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 413.4, "completion_year": 2012 },
    { "rank": 40, "name": "Al Hamra Tower", "name_zh": "阿爾哈姆拉塔", "city": "Kuwait City", "city_zh": "科威特市", "country": "Kuwait", "country_zh": "科威特", "height_m": 412.6, "completion_year": 2011 },
    { "rank": 41, "name": "International Finance Centre", "name_zh": "國際金融中心", "city": "Hong Kong", "city_zh": "香港", "country": "Hong Kong", "country_zh": "香港", "height_m": 412, "completion_year": 2003 },
    { "rank": 42, "name": "Haeundae LCT Landmark Tower", "name_zh": "海雲臺 LCT 地標塔", "city": "Busan", "city_zh": "釜山", "country": "South Korea", "country_zh": "南韓", "height_m": 411.6, "completion_year": 2019 },
    { "rank": 43, "name": "Ningbo Central Plaza", "name_zh": "寧波中心廣場", "city": "Ningbo", "city_zh": "寧波", "country": "China", "country_zh": "中國", "height_m": 409, "completion_year": 2024 },
    { "rank": 44, "name": "Guangxi China Resources Tower", "name_zh": "廣西華潤大廈", "city": "Nanning", "city_zh": "南寧", "country": "China", "country_zh": "中國", "height_m": 402.7, "completion_year": 2020 },
    { "rank": 45, "name": "Guiyang International Financial Center T1", "name_zh": "貴陽國際金融中心 T1", "city": "Guiyang", "city_zh": "貴陽", "country": "China", "country_zh": "中國", "height_m": 401, "completion_year": 2020 },
    { "rank": 46, "name": "Iconic Tower", "name_zh": "標誌塔", "city": "New Administrative Capital", "city_zh": "新行政首都", "country": "Egypt", "country_zh": "埃及", "height_m": 393.8, "completion_year": 2024 },
    { "rank": 47, "name": "China Merchants Bank Headquarters", "name_zh": "招商銀行總部大廈", "city": "Shenzhen", "city_zh": "深圳", "country": "China", "country_zh": "中國", "height_m": 393, "completion_year": 2024 },
    { "rank": 48, "name": "China Resources Tower", "name_zh": "華潤大廈 (春筍)", "city": "Shenzhen", "city_zh": "深圳", "country": "China", "country_zh": "中國", "height_m": 392.5, "completion_year": 2018 },
    { "rank": 49, "name": "23 Marina", "name_zh": "23 瑪麗娜", "city": "Dubai", "city_zh": "杜拜", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 392.4, "completion_year": 2012 },
    { "rank": 50, "name": "CITIC Plaza", "name_zh": "中信廣場", "city": "Guangzhou", "city_zh": "廣州", "country": "China", "country_zh": "中國", "height_m": 390.2, "completion_year": 1996 },
    { "rank": 51, "name": "Citymark Centre", "name_zh": "城脈中心", "city": "Shenzhen", "city_zh": "深圳", "country": "China", "country_zh": "中國", "height_m": 388.3, "completion_year": 2022 },
    { "rank": 52, "name": "Shum Yip Upperhills Tower 1", "name_zh": "深業上城 T1", "city": "Shenzhen", "city_zh": "深圳", "country": "China", "country_zh": "中國", "height_m": 388.1, "completion_year": 2020 },
    { "rank": 53, "name": "30 Hudson Yards", "name_zh": "哈德遜城市廣場30號", "city": "New York City", "city_zh": "紐約市", "country": "United States", "country_zh": "美國", "height_m": 387.1, "completion_year": 2019 },
    { "rank": 54, "name": "Capital Market Authority", "name_zh": "資本市場管理局總部", "city": "Riyadh", "city_zh": "Riyadh", "country": "Saudi Arabia", "country_zh": "沙烏地阿拉伯", "height_m": 385, "completion_year": 2021 },
    { "rank": 55, "name": "Public Investment Fund (PIF) Tower", "name_zh": "公共投資基金大廈", "city": "Riyadh", "city_zh": "Riyadh", "country": "Saudi Arabia", "country_zh": "沙烏地阿拉伯", "height_m": 385, "completion_year": 2021 },
    { "rank": 56, "name": "Shun Hing Square", "name_zh": "信興廣場 (地王大廈)", "city": "Shenzhen", "city_zh": "深圳", "country": "China", "country_zh": "中國", "height_m": 384, "completion_year": 1996 },
    { "rank": 57, "name": "Eton Place Dalian Tower 1", "name_zh": "大連裕景中心 T1", "city": "Dalian", "city_zh": "大連", "country": "China", "country_zh": "中國", "height_m": 383.2, "completion_year": 2016 },
    { "rank": 58, "name": "Autograph Tower", "name_zh": "親筆塔", "city": "Jakarta", "city_zh": "雅加達", "country": "Indonesia", "country_zh": "印尼", "height_m": 382.9, "completion_year": 2022 },
    { "rank": 59, "name": "Logan Century Center 1", "name_zh": "龍光世紀中心 1", "city": "Nanning", "city_zh": "南寧", "country": "China", "country_zh": "中國", "height_m": 381.3, "completion_year": 2018 },
    { "rank": 60, "name": "Burj Mohammed bin Rashid", "name_zh": "穆罕默德·本·拉希德塔", "city": "Abu Dhabi", "city_zh": "阿布達比", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 381.2, "completion_year": 2014 },
    { "rank": 61, "name": "Empire State Building", "name_zh": "帝國大廈", "city": "New York City", "city_zh": "紐約市", "country": "United States", "country_zh": "美國", "height_m": 381, "completion_year": 1931 },
    { "rank": 62, "name": "Elite Residence", "name_zh": "精英住宅區", "city": "Dubai", "city_zh": "杜拜", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 380.5, "completion_year": 2012 },
    { "rank": 63, "name": "Riverview Plaza", "name_zh": "武漢長江航運中心", "city": "Wuhan", "city_zh": "武漢", "country": "China", "country_zh": "中國", "height_m": 376, "completion_year": 2023 },
    { "rank": 64, "name": "Dabaihui Plaza", "name_zh": "大百匯廣場", "city": "Shenzhen", "city_zh": "深圳", "country": "China", "country_zh": "中國", "height_m": 375.6, "completion_year": 2021 },
    { "rank": 65, "name": "Guangdong Business Center", "name_zh": "廣東商務中心", "city": "Guangzhou", "city_zh": "廣州", "country": "China", "country_zh": "中國", "height_m": 375.5, "completion_year": 2024 },
    { "rank": 66, "name": "Central Plaza", "name_zh": "中環廣場", "city": "Hong Kong", "city_zh": "香港", "country": "Hong Kong", "country_zh": "香港", "height_m": 373.9, "completion_year": 1992 },
    { "rank": 67, "name": "Federation Tower (East)", "name_zh": "聯邦塔 (東塔)", "city": "Moscow", "city_zh": "莫斯科", "country": "Russia", "country_zh": "俄羅斯", "height_m": 373.7, "completion_year": 2017 },
    { "rank": 68, "name": "Hengfeng Guiyang Center Tower 1", "name_zh": "恒豐貴陽中心 T1", "city": "Guiyang", "city_zh": "貴陽", "country": "China", "country_zh": "中國", "height_m": 373.5, "completion_year": 2023 },
    { "rank": 69, "name": "Dalian International Trade Center", "name_zh": "大連國際貿易中心", "city": "Dalian", "city_zh": "大連", "country": "China", "country_zh": "中國", "height_m": 370.2, "completion_year": 2019 },
    { "rank": 70, "name": "Shanghai International Trade Center", "name_zh": "上海國際貿易中心", "city": "Shanghai", "city_zh": "上海", "country": "China", "country_zh": "中國", "height_m": 370, "completion_year": 2024 },
    { "rank": 71, "name": "Haitian Center Tower 2", "name_zh": "海天中心 T2", "city": "Qingdao", "city_zh": "青島", "country": "China", "country_zh": "中國", "height_m": 368.9, "completion_year": 2021 },
    { "rank": 72, "name": "Golden Eagle Tiandi Tower A", "name_zh": "金鷹天地 T1", "city": "Nanjing", "city_zh": "南京", "country": "China", "country_zh": "中國", "height_m": 368.1, "completion_year": 2019 },
    { "rank": 73, "name": "Bank of China Tower", "name_zh": "中銀大廈", "city": "Hong Kong", "city_zh": "香港", "country": "Hong Kong", "country_zh": "香港", "height_m": 367.4, "completion_year": 1990 },
    { "rank": 74, "name": "Bank of America Tower", "name_zh": "美國銀行大廈", "city": "New York City", "city_zh": "紐約市", "country": "United States", "country_zh": "美國", "height_m": 365.8, "completion_year": 2009 },
    { "rank": 75, "name": "Ciel Dubai Marina", "name_zh": "希爾大廈", "city": "Dubai", "city_zh": "杜拜", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 365.5, "completion_year": 2024 },
    { "rank": 76, "name": "St. Regis Chicago", "name_zh": "芝加哥瑞吉酒店", "city": "Chicago", "city_zh": "芝加哥", "country": "United States", "country_zh": "美國", "height_m": 362.9, "completion_year": 2020 },
    { "rank": 77, "name": "Almas Tower", "name_zh": "阿爾瑪斯塔", "city": "Dubai", "city_zh": "杜拜", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 360, "completion_year": 2008 },
    { "rank": 78, "name": "Huiyun Center", "name_zh": "匯雲中心", "city": "Shenzhen", "city_zh": "深圳", "country": "China", "country_zh": "中國", "height_m": 359.2, "completion_year": 2023 },
    { "rank": 79, "name": "Hanking Center", "name_zh": "漢京中心", "city": "Shenzhen", "city_zh": "深圳", "country": "China", "country_zh": "中國", "height_m": 358.9, "completion_year": 2018 },
    { "rank": 80, "name": "Greenland Group Suzhou Center", "name_zh": "綠地集團蘇州中心", "city": "Suzhou", "city_zh": "蘇州", "country": "China", "country_zh": "中國", "height_m": 358, "completion_year": 2024 },
    { "rank": 81, "name": "Gevora Hotel", "name_zh": "吉沃拉酒店", "city": "Dubai", "city_zh": "杜拜", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 356.3, "completion_year": 2017 },
    { "rank": 82, "name": "Galaxy World Tower 1", "name_zh": "星河雙子塔", "city": "Shenzhen", "city_zh": "深圳", "country": "China", "country_zh": "中國", "height_m": 356, "completion_year": 2023 },
    { "rank": 83, "name": "JW Marriott Marquis Dubai Tower 1", "name_zh": "萬豪侯爵酒店 1", "city": "Dubai", "city_zh": "杜拜", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 355.4, "completion_year": 2012 },
    { "rank": 84, "name": "Emirates Office Tower", "name_zh": "阿聯酋辦公大樓", "city": "Dubai", "city_zh": "杜拜", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 354.6, "completion_year": 2000 },
    { "rank": 85, "name": "Raffles City Chongqing T3N", "name_zh": "來福士廣場 T3N", "city": "Chongqing", "city_zh": "重慶", "country": "China", "country_zh": "中國", "height_m": 354.5, "completion_year": 2019 },
    { "rank": 86, "name": "OKO - South Tower", "name_zh": "OKO - 南塔", "city": "Moscow", "city_zh": "莫斯科", "country": "Russia", "country_zh": "俄羅斯", "height_m": 354.2, "completion_year": 2015 },
    { "rank": 87, "name": "CBRT Tower", "name_zh": "土耳其央行大廈", "city": "Istanbul", "city_zh": "伊斯坦堡", "country": "Turkey", "country_zh": "土耳其", "height_m": 352, "completion_year": 2024 },
    { "rank": 88, "name": "SkyTower at Pinnacle One Yonge", "name_zh": "天空之塔", "city": "Toronto", "city_zh": "多倫多", "country": "Canada", "country_zh": "加拿大", "height_m": 351.4, "completion_year": 2024 },
    { "rank": 89, "name": "Forum 66 Tower 1", "name_zh": "市府恒隆廣場 T1", "city": "Shenyang", "city_zh": "瀋陽", "country": "China", "country_zh": "中國", "height_m": 350.6, "completion_year": 2015 },
    { "rank": 90, "name": "The Pinnacle", "name_zh": "廣晟國際大廈", "city": "Guangzhou", "city_zh": "廣州", "country": "China", "country_zh": "中國", "height_m": 350.3, "completion_year": 2012 },
    { "rank": 91, "name": "Xi'an Glory International Financial Center", "name_zh": "西安國瑞第一樂府", "city": "Xi'an", "city_zh": "西安", "country": "China", "country_zh": "中國", "height_m": 350, "completion_year": 2022 },
    { "rank": 92, "name": "Spring City 66", "name_zh": "昆明恒隆廣場", "city": "Kunming", "city_zh": "昆明", "country": "China", "country_zh": "中國", "height_m": 349, "completion_year": 2019 },
    { "rank": 93, "name": "85 Sky Tower", "name_zh": "高雄 85 大樓", "city": "Kaohsiung", "city_zh": "高雄", "country": "Taiwan", "country_zh": "台灣", "height_m": 348, "completion_year": 1997 },
    { "rank": 94, "name": "Aon Center", "name_zh": "怡安中心", "city": "Chicago", "city_zh": "芝加哥", "country": "United States", "country_zh": "美國", "height_m": 346.3, "completion_year": 1973 },
    { "rank": 95, "name": "The Center", "name_zh": "中環中心", "city": "Hong Kong", "city_zh": "香港", "country": "Hong Kong", "country_zh": "香港", "height_m": 346, "completion_year": 1998 },
    { "rank": 96, "name": "Neva Towers 2", "name_zh": "涅瓦塔 2", "city": "Moscow", "city_zh": "莫斯科", "country": "Russia", "country_zh": "俄羅斯", "height_m": 345, "completion_year": 2020 },
    { "rank": 97, "name": "Xiamen Cross Strait Financial Centre", "name_zh": "廈門海峽交流中心", "city": "Xiamen", "city_zh": "廈門", "country": "China", "country_zh": "中國", "height_m": 343.9, "completion_year": 2019 },
    { "rank": 98, "name": "John Hancock Center", "name_zh": "約翰·漢考克中心", "city": "Chicago", "city_zh": "芝加哥", "country": "United States", "country_zh": "美國", "height_m": 343.7, "completion_year": 1969 },
    { "rank": 99, "name": "ADNOC Headquarters", "name_zh": "阿布札比國家石油公司總部", "city": "Abu Dhabi", "city_zh": "阿布達比", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 342, "completion_year": 2015 },
    { "rank": 100, "name": "Ahmed Abdul Rahim Al Attar Tower", "name_zh": "阿爾阿塔爾塔", "city": "Dubai", "city_zh": "杜拜", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 342, "completion_year": 2018 },
    { "rank": 101, "name": "Tianjin World Financial Center", "name_zh": "天津環球金融中心", "city": "Tianjin", "city_zh": "天津", "country": "China", "country_zh": "中國", "height_m": 337, "completion_year": 2011 },
    { "rank": 102, "name": "DAMAC Heights", "name_zh": "達馬克海景大廈", "city": "Dubai", "city_zh": "杜拜", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 335.1, "completion_year": 2018 },
    { "rank": 103, "name": "Shimao International Plaza", "name_zh": "上海世茂國際廣場", "city": "Shanghai", "city_zh": "上海", "country": "China", "country_zh": "中國", "height_m": 333.3, "completion_year": 2006 },
    { "rank": 104, "name": "Rose Tower", "name_zh": "玫瑰塔", "city": "Dubai", "city_zh": "杜拜", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 333, "completion_year": 2007 },
    { "rank": 105, "name": "Wenzhou World Trade Center", "name_zh": "溫州世界貿易中心", "city": "Wenzhou", "city_zh": "溫州", "country": "China", "country_zh": "中國", "height_m": 333, "completion_year": 2010 },
    { "rank": 106, "name": "Minsheng Bank Building", "name_zh": "民生銀行大廈", "city": "Wuhan", "city_zh": "武漢", "country": "China", "country_zh": "中國", "height_m": 331, "completion_year": 2008 },
    { "rank": 107, "name": "China World Trade Center Tower III", "name_zh": "中國國貿大廈A座", "city": "Beijing", "city_zh": "北京", "country": "China", "country_zh": "中國", "height_m": 330, "completion_year": 2010 },
    { "rank": 108, "name": "Ryugyong Hotel", "name_zh": "柳京飯店", "city": "Pyongyang", "city_zh": "平壤", "country": "North Korea", "country_zh": "北韓", "height_m": 330, "completion_year": 1992 },
    { "rank": 109, "name": "Yuexiu Fortune Center Tower 1", "name_zh": "越秀財富中心 T1", "city": "Wuhan", "city_zh": "武漢", "country": "China", "country_zh": "中國", "height_m": 330, "completion_year": 2017 },
    { "rank": 110, "name": "Zhuhai Tower", "name_zh": "珠海中心大廈", "city": "Zhuhai", "city_zh": "珠海", "country": "China", "country_zh": "中國", "height_m": 330, "completion_year": 2017 },
    { "rank": 111, "name": "Hon Kwok City Center", "name_zh": "漢國城市商業中心", "city": "Shenzhen", "city_zh": "深圳", "country": "China", "country_zh": "中國", "height_m": 329.4, "completion_year": 2017 },
    { "rank": 112, "name": "Al Yaqoub Tower", "name_zh": "阿爾雅各布塔", "city": "Dubai", "city_zh": "杜拜", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 328, "completion_year": 2013 },
    { "rank": 113, "name": "Longxi International Hotel", "name_zh": "龍希國際大酒店", "city": "Jiangyin", "city_zh": "江陰", "country": "China", "country_zh": "中國", "height_m": 328, "completion_year": 2011 },
    { "rank": 114, "name": "The Wharf Times Square", "name_zh": "無錫九龍倉時代廣場", "city": "Wuxi", "city_zh": "無錫", "country": "China", "country_zh": "中國", "height_m": 328, "completion_year": 2014 },
    { "rank": 115, "name": "Wuxi Suning Plaza Tower 1", "name_zh": "無錫蘇寧廣場 1 座", "city": "Wuxi", "city_zh": "無錫", "country": "China", "country_zh": "中國", "height_m": 328, "completion_year": 2014 },
    { "rank": 116, "name": "Baoneng Center", "name_zh": "寶能中心", "city": "Shenzhen", "city_zh": "深圳", "country": "China", "country_zh": "中國", "height_m": 327.3, "completion_year": 2018 },
    { "rank": 117, "name": "The Address Boulevard", "name_zh": "地址大道酒店", "city": "Dubai", "city_zh": "杜拜", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 327, "completion_year": 2017 },
    { "rank": 118, "name": "Index Tower", "name_zh": "指數大廈", "city": "Dubai", "city_zh": "杜拜", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 326, "completion_year": 2010 },
    { "rank": 119, "name": "The Landmark", "name_zh": "阿布札比地標塔", "city": "Abu Dhabi", "city_zh": "阿布達比", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 324, "completion_year": 2013 },
    { "rank": 120, "name": "Q1 Tower", "name_zh": "Q1大廈", "city": "Gold Coast", "city_zh": "黃金海岸", "country": "Australia", "country_zh": "澳洲", "height_m": 322.5, "completion_year": 2005 },
    { "rank": 121, "name": "Burj Al Arab", "name_zh": "帆船酒店", "city": "Dubai", "city_zh": "杜拜", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 321, "completion_year": 1999 },
    { "rank": 122, "name": "Guangxi Finance Plaza", "name_zh": "廣西金融廣場", "city": "Nanning", "city_zh": "南寧", "country": "China", "country_zh": "中國", "height_m": 321, "completion_year": 2017 },
    { "rank": 123, "name": "Nina Tower", "name_zh": "如心廣場", "city": "Hong Kong", "city_zh": "香港", "country": "Hong Kong", "country_zh": "香港", "height_m": 320.4, "completion_year": 2008 },
    { "rank": 124, "name": "Farglory Financial Center", "name_zh": "遠雄金融中心", "city": "Taipei", "city_zh": "台北", "country": "Taiwan", "country_zh": "台灣", "height_m": 320, "completion_year": 2012 },
    { "rank": 125, "name": "Sinar Mas Center 1", "name_zh": "白玉蘭廣場", "city": "Shanghai", "city_zh": "上海", "country": "China", "country_zh": "中國", "height_m": 320, "completion_year": 2017 },
    { "rank": 126, "name": "Chrysler Building", "name_zh": "克萊斯勒大廈", "city": "New York City", "city_zh": "紐約市", "country": "United States", "country_zh": "美國", "height_m": 318.9, "completion_year": 1930 },
    { "rank": 127, "name": "New York Times Building", "name_zh": "紐約時報大廈", "city": "New York City", "city_zh": "紐約市", "country": "United States", "country_zh": "美國", "height_m": 318.9, "completion_year": 2007 },
    { "rank": 128, "name": "HHHR Tower", "name_zh": "藍天大廈", "city": "Dubai", "city_zh": "杜拜", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 317, "completion_year": 2011 },
    { "rank": 129, "name": "Chongqing IFS T1", "name_zh": "重慶國際金融中心 T1", "city": "Chongqing", "city_zh": "重慶", "country": "China", "country_zh": "中國", "height_m": 316.3, "completion_year": 2017 },
    { "rank": 130, "name": "Nanjing International Youth Cultural Centre Tower 1", "name_zh": "南京國際青年文化中心 T1", "city": "Nanjing", "city_zh": "南京", "country": "China", "country_zh": "中國", "height_m": 314.5, "completion_year": 2018 },
    { "rank": 131, "name": "MahaNakhon", "name_zh": "大都會大廈", "city": "Bangkok", "city_zh": "曼谷", "country": "Thailand", "country_zh": "泰國", "height_m": 314.2, "completion_year": 2016 },
    { "rank": 132, "name": "Bank of America Plaza", "name_zh": "美國銀行廣場", "city": "Atlanta", "city_zh": "亞特蘭大", "country": "United States", "country_zh": "美國", "height_m": 311.8, "completion_year": 1992 },
    { "rank": 133, "name": "Abu Dhabi Plaza", "name_zh": "阿布札比廣場", "city": "Astana", "city_zh": "阿斯塔納", "country": "Kazakhstan", "country_zh": "哈薩克", "height_m": 311, "completion_year": 2020 },
    { "rank": 134, "name": "US Bank Tower", "name_zh": "聯邦銀行大廈", "city": "Los Angeles", "city_zh": "洛杉磯", "country": "United States", "country_zh": "美國", "height_m": 310.3, "completion_year": 1989 },
    { "rank": 135, "name": "Menara Telekom", "name_zh": "電訊大廈", "city": "Kuala Lumpur", "city_zh": "吉隆坡", "country": "Malaysia", "country_zh": "馬來西亞", "height_m": 310, "completion_year": 2001 },
    { "rank": 136, "name": "Ocean Heights", "name_zh": "海洋高度大廈", "city": "Dubai", "city_zh": "杜拜", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 310, "completion_year": 2010 },
    { "rank": 137, "name": "Fortune Center", "name_zh": "廣州財富中心", "city": "Guangzhou", "city_zh": "廣州", "country": "China", "country_zh": "中國", "height_m": 309.4, "completion_year": 2015 },
    { "rank": 138, "name": "Pearl River Tower", "name_zh": "珠江城大廈", "city": "Guangzhou", "city_zh": "廣州", "country": "China", "country_zh": "中國", "height_m": 309.4, "completion_year": 2013 },
    { "rank": 139, "name": "Jumeirah Emirates Towers Hotel", "name_zh": "朱美拉阿聯酋酒店", "city": "Dubai", "city_zh": "杜拜", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 309, "completion_year": 2000 },
    { "rank": 140, "name": "One Island East", "name_zh": "港島東中心", "city": "Hong Kong", "city_zh": "香港", "country": "Hong Kong", "country_zh": "香港", "height_m": 308, "completion_year": 2008 },
    { "rank": 141, "name": "Burj Rafal", "name_zh": "拉法爾塔", "city": "Riyadh", "city_zh": "Riyadh", "country": "Saudi Arabia", "country_zh": "沙烏地阿拉伯", "height_m": 307.9, "completion_year": 2014 },
    { "rank": 142, "name": "Franklin Center", "name_zh": "富蘭克林中心", "city": "Chicago", "city_zh": "芝加哥", "country": "United States", "country_zh": "美國", "height_m": 306.9, "completion_year": 1989 },
    { "rank": 143, "name": "East Pacific Center Tower A", "name_zh": "東海商務中心 A 座", "city": "Shenzhen", "city_zh": "深圳", "country": "China", "country_zh": "中國", "height_m": 306, "completion_year": 2013 },
    { "rank": 144, "name": "The Address Beach Resort", "name_zh": "地址海灘度假村", "city": "Dubai", "city_zh": "杜拜", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 301, "completion_year": 2020 },
    { "rank": 145, "name": "Abeno Harukas", "name_zh": "阿倍野Harukas", "city": "Osaka", "city_zh": "大阪", "country": "Japan", "country_zh": "日本", "height_m": 300, "completion_year": 2014 },
    { "rank": 146, "name": "Arraysa Tower 2", "name_zh": "阿萊薩塔 2", "city": "Kuwait City", "city_zh": "科威特市", "country": "Kuwait", "country_zh": "科威特", "height_m": 300, "completion_year": 2014 },
    { "rank": 147, "name": "Commerzbank Tower", "name_zh": "商業銀行大廈", "city": "Frankfurt", "city_zh": "法蘭克福", "country": "Germany", "country_zh": "德國", "height_m": 300, "completion_year": 1997 },
    { "rank": 148, "name": "Doosan Haeundae We've the Zenith Tower A", "name_zh": "釜山海雲臺斗山 Zenith A 座", "city": "Busan", "city_zh": "釜山", "country": "South Korea", "country_zh": "南韓", "height_m": 300, "completion_year": 2011 },
    { "rank": 149, "name": "Gran Torre Santiago", "name_zh": "聖地亞哥大廈", "city": "Santiago", "city_zh": "聖地牙哥", "country": "Chile", "country_zh": "智利", "height_m": 300, "completion_year": 2013 },
    { "rank": 150, "name": "Shimao Yangtze River Tower 1", "name_zh": "南京世茂外灘新城 1 號樓", "city": "Nanjing", "city_zh": "南京", "country": "China", "country_zh": "中國", "height_m": 300, "completion_year": 2011 },
    { "rank": 151, "name": "The Hub T1", "name_zh": "南京匯中心 T1", "city": "Nanjing", "city_zh": "南京", "country": "China", "country_zh": "中國", "height_m": 299, "completion_year": 2020 },
    { "rank": 152, "name": "First Canadian Place", "name_zh": "第一加拿大廣場", "city": "Toronto", "city_zh": "多倫多", "country": "Canada", "country_zh": "加拿大", "height_m": 298.1, "completion_year": 1975 },
    { "rank": 153, "name": "Honglong Century Plaza", "name_zh": "宏隆世紀廣場", "city": "Shenzhen", "city_zh": "深圳", "country": "China", "country_zh": "中國", "height_m": 298.0, "completion_year": 2013 },
    { "rank": 154, "name": "Shanghai Wheelock Square", "name_zh": "上海會德豐國際廣場", "city": "Shanghai", "city_zh": "上海", "country": "China", "country_zh": "中國", "height_m": 298, "completion_year": 2010 },
    { "rank": 155, "name": "Four World Trade Center", "name_zh": "世界貿易中心四號大樓", "city": "New York City", "city_zh": "紐約市", "country": "United States", "country_zh": "美國", "height_m": 297.7, "completion_year": 2013 },
    { "rank": 156, "name": "Eureka Tower", "name_zh": "發現大樓", "city": "Melbourne", "city_zh": "墨爾本", "country": "Australia", "country_zh": "澳洲", "height_m": 297.3, "completion_year": 2006 },
    { "rank": 157, "name": "Comcast Center", "name_zh": "康卡斯特中心", "city": "Philadelphia", "city_zh": "費城", "country": "United States", "country_zh": "美國", "height_m": 296.7, "completion_year": 2008 },
    { "rank": 158, "name": "Emirates Crown", "name_zh": "皇冠大廈", "city": "Dubai", "city_zh": "杜拜", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 296, "completion_year": 2008 },
    { "rank": 159, "name": "Yokohama Landmark Tower", "name_zh": "橫濱地標大廈", "city": "Yokohama", "city_zh": "橫濱", "country": "Japan", "country_zh": "日本", "height_m": 296, "completion_year": 1993 },
    { "rank": 160, "name": "311 South Wacker Drive", "name_zh": "南威克大道311號", "city": "Chicago", "city_zh": "芝加哥", "country": "United States", "country_zh": "美國", "height_m": 293, "completion_year": 1990 },
    { "rank": 161, "name": "SEG Plaza", "name_zh": "賽格廣場", "city": "Shenzhen", "city_zh": "深圳", "country": "China", "country_zh": "中國", "height_m": 291.6, "completion_year": 2000 },
    { "rank": 162, "name": "Global Trade Plaza", "name_zh": "環球經貿中心", "city": "Dongguan", "city_zh": "東莞", "country": "China", "country_zh": "中國", "height_m": 289, "completion_year": 2011 },
    { "rank": 163, "name": "Key Tower", "name_zh": "鑰匙塔", "city": "Cleveland", "city_zh": "克里夫蘭", "country": "United States", "country_zh": "美國", "height_m": 288.7, "completion_year": 1991 },
    { "rank": 164, "name": "One Liberty Place", "name_zh": "自由廣場一號", "city": "Philadelphia", "city_zh": "費城", "country": "United States", "country_zh": "美國", "height_m": 288, "completion_year": 1987 },
    { "rank": 165, "name": "Plaza 66 Tower 1", "name_zh": "恒隆廣場一期", "city": "Shanghai", "city_zh": "上海", "country": "China", "country_zh": "中國", "height_m": 288, "completion_year": 2001 },
    { "rank": 166, "name": "Sulafa Tower", "name_zh": "蘇拉法塔", "city": "Dubai", "city_zh": "杜拜", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 288, "completion_year": 2010 },
    { "rank": 167, "name": "Millennium Tower", "name_zh": "千禧大廈", "city": "Dubai", "city_zh": "杜拜", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 285, "completion_year": 2006 },
    { "rank": 168, "name": "Tomorrow Square", "name_zh": "明天廣場", "city": "Shanghai", "city_zh": "上海", "country": "China", "country_zh": "中國", "height_m": 285, "completion_year": 2003 },
    { "rank": 169, "name": "Columbia Center", "name_zh": "哥倫比亞中心", "city": "Seattle", "city_zh": "西雅圖", "country": "United States", "country_zh": "美國", "height_m": 284.2, "completion_year": 1985 },
    { "rank": 170, "name": "Chongqing World Trade Center", "name_zh": "重慶世界貿易中心", "city": "Chongqing", "city_zh": "重慶", "country": "China", "country_zh": "中國", "height_m": 283.1, "completion_year": 2005 },
    { "rank": 171, "name": "Cheung Kong Center", "name_zh": "長江集團中心", "city": "Hong Kong", "city_zh": "香港", "country": "Hong Kong", "country_zh": "香港", "height_m": 283, "completion_year": 1999 },
    { "rank": 172, "name": "Trump Building", "name_zh": "川普大樓", "city": "New York City", "city_zh": "紐約市", "country": "United States", "country_zh": "美國", "height_m": 283, "completion_year": 1930 },
    { "rank": 173, "name": "Al Fattan Marine Towers", "name_zh": "阿爾法坦海洋雙塔", "city": "Dubai", "city_zh": "杜拜", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 281, "completion_year": 2006 },
    { "rank": 174, "name": "Bank of America Plaza", "name_zh": "美國銀行廣場", "city": "Dallas", "city_zh": "達拉斯", "country": "United States", "country_zh": "美國", "height_m": 281, "completion_year": 1985 },
    { "rank": 175, "name": "OUB Centre", "name_zh": "華聯銀行大廈", "city": "Singapore", "city_zh": "新加坡", "country": "Singapore", "country_zh": "新加坡", "height_m": 280, "completion_year": 1986 },
    { "rank": 176, "name": "Republic Plaza", "name_zh": "共和大廈", "city": "Singapore", "city_zh": "新加坡", "country": "Singapore", "country_zh": "新加坡", "height_m": 280, "completion_year": 1995 },
    { "rank": 177, "name": "UOB Plaza One", "name_zh": "大華銀行大廈", "city": "Singapore", "city_zh": "新加坡", "country": "Singapore", "country_zh": "新加坡", "height_m": 280, "completion_year": 1992 },
    { "rank": 178, "name": "Citigroup Center", "name_zh": "花旗集團中心", "city": "New York City", "city_zh": "紐約市", "country": "United States", "country_zh": "美國", "height_m": 279, "completion_year": 1977 },
    { "rank": 179, "name": "Jumeirah Lake Towers", "name_zh": "朱美拉湖塔", "city": "Dubai", "city_zh": "杜拜", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 279, "completion_year": 2008 },
    { "rank": 180, "name": "Diwang International Commerce Center", "name_zh": "地王國際商貿中心", "city": "Nanning", "city_zh": "南寧", "country": "China", "country_zh": "中國", "height_m": 276, "completion_year": 2006 },
    { "rank": 181, "name": "Scotia Plaza", "name_zh": "豐業銀行廣場", "city": "Toronto", "city_zh": "多倫多", "country": "Canada", "country_zh": "加拿大", "height_m": 275, "completion_year": 1988 },
    { "rank": 182, "name": "Williams Tower", "name_zh": "威廉斯大廈", "city": "Houston", "city_zh": "休士頓", "country": "United States", "country_zh": "美國", "height_m": 275, "completion_year": 1983 },
    { "rank": 183, "name": "BJWTO Tower", "name_zh": "北京世界貿易中心", "city": "Beijing", "city_zh": "北京", "country": "China", "country_zh": "中國", "height_m": 274, "completion_year": 2010 },
    { "rank": 184, "name": "Wuhan World Trade Tower", "name_zh": "武漢世界貿易大廈", "city": "Wuhan", "city_zh": "武漢", "country": "China", "country_zh": "中國", "height_m": 273, "completion_year": 1998 },
    { "rank": 185, "name": "Aura", "name_zh": "極光大廈", "city": "Toronto", "city_zh": "多倫多", "country": "Canada", "country_zh": "加拿大", "height_m": 272, "completion_year": 2014 },
    { "rank": 186, "name": "The Cullinan North Tower", "name_zh": "天璽(北)", "city": "Hong Kong", "city_zh": "香港", "country": "Hong Kong", "country_zh": "香港", "height_m": 270, "completion_year": 2008 },
    { "rank": 187, "name": "The Cullinan South Tower", "name_zh": "天璽(南)", "city": "Hong Kong", "city_zh": "香港", "country": "Hong Kong", "country_zh": "香港", "height_m": 270, "completion_year": 2008 },
    { "rank": 188, "name": "OUE Downtown 1", "name_zh": "華聯城一期", "city": "Singapore", "city_zh": "新加坡", "country": "Singapore", "country_zh": "新加坡", "height_m": 268, "completion_year": 1976 },
    { "rank": 189, "name": "Al Kazim Towers", "name_zh": "卡齊姆塔", "city": "Dubai", "city_zh": "杜拜", "country": "United Arab Emirates", "country_zh": "阿拉伯聯合大公國", "height_m": 265, "completion_year": 2008 },
    { "rank": 190, "name": "Grand Gateway Shanghai I", "name_zh": "港匯恆隆廣場一期", "city": "Shanghai", "city_zh": "上海", "country": "China", "country_zh": "中國", "height_m": 262, "completion_year": 2005 },
    { "rank": 191, "name": "Grand Gateway Shanghai II", "name_zh": "港匯恆隆廣場二期", "city": "Shanghai", "city_zh": "上海", "country": "China", "country_zh": "中國", "height_m": 262, "completion_year": 2005 },
    { "rank": 192, "name": "Nathani Heights", "name_zh": "納塔尼精華", "city": "Mumbai", "city_zh": "孟買", "country": "India", "country_zh": "印度", "height_m": 262, "completion_year": 2020 },
    { "rank": 193, "name": "BOC Tower", "name_zh": "中銀大廈", "city": "Shanghai", "city_zh": "上海", "country": "China", "country_zh": "中國", "height_m": 261, "completion_year": 2000 },
    { "rank": 194, "name": "Banyan Tree Residences", "name_zh": "悅榕莊住宅塔", "city": "Panama City", "city_zh": "巴拿馬城", "country": "Panama", "country_zh": "巴拿馬", "height_m": 260, "completion_year": 2012 },
    { "rank": 195, "name": "Isis", "name_zh": "伊西斯塔", "city": "Miami", "city_zh": "Miami", "country": "United States", "country_zh": "美國", "height_m": 260, "completion_year": 2008 },
    { "rank": 196, "name": "LCT Residential Tower", "name_zh": "LCT 住宅大樓", "city": "Busan", "city_zh": "釜山", "country": "South Korea", "country_zh": "南韓", "height_m": 260, "completion_year": 2019 },
    { "rank": 197, "name": "PBCOM Tower", "name_zh": "菲律賓交通銀行大廈", "city": "Makati", "city_zh": "馬卡蒂", "country": "Philippines", "country_zh": "菲律賓", "height_m": 259, "completion_year": 2000 },
    { "rank": 198, "name": "Kempinski Hotel Doha", "name_zh": "多哈凱賓斯基酒店", "city": "Doha", "city_zh": "杜哈", "country": "Qatar", "country_zh": "卡達", "height_m": 256, "completion_year": 2015 },
    { "rank": 199, "name": "The Imperial I", "name_zh": "帝國大廈 I", "city": "Mumbai", "city_zh": "孟買", "country": "India", "country_zh": "印度", "height_m": 256, "completion_year": 2010 },
    { "rank": 200, "name": "The Imperial II", "name_zh": "帝國大廈 II", "city": "Mumbai", "city_zh": "孟買", "country": "India", "country_zh": "印度", "height_m": 256, "completion_year": 2010 }
];
